// <auto-generated />
using System;
using GloboChat.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GloboChat.Infra.Data.Migrations
{
    [DbContext(typeof(GloboChatContext))]
    [Migration("20200214222848_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("loginId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("loginId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Canal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Canais");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Final")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramaAtual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanalId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<int>("nivelAcesso")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("loginId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("loginId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.SalaChat", b =>
                {
                    b.Property<int>("IdChat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdChat", "IdPessoa");

                    b.HasIndex("IdPessoa");

                    b.ToTable("SalasChat");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Facebook")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Twitter")
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .HasColumnType("TEXT");

                    b.Property<int?>("pessoaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("pessoaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Admin", b =>
                {
                    b.HasOne("GloboChat.Dominio.Entidades.Login", "login")
                        .WithMany()
                        .HasForeignKey("loginId");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Chat", b =>
                {
                    b.HasOne("GloboChat.Dominio.Entidades.Canal", null)
                        .WithMany("Chats")
                        .HasForeignKey("CanalId");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Pessoa", b =>
                {
                    b.HasOne("GloboChat.Dominio.Entidades.Login", "login")
                        .WithMany()
                        .HasForeignKey("loginId");
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.SalaChat", b =>
                {
                    b.HasOne("GloboChat.Dominio.Entidades.Chat", "Chat")
                        .WithMany("SalasChat")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GloboChat.Dominio.Entidades.Pessoa", "Pessoa")
                        .WithMany("SalasChat")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloboChat.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("GloboChat.Dominio.Entidades.Pessoa", "pessoa")
                        .WithMany()
                        .HasForeignKey("pessoaId");
                });
#pragma warning restore 612, 618
        }
    }
}
